spring:
  datasource:
    url: jdbc:mysql://localhost:3307/trackers?serverTimezone=Asia/Seoul
    username: trackers
    password: qhddnfl
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update # 테이블을 drop하지 않음 data를 계속 쓸 수 있음
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
#        show_sql: true   # sout 으로 출력

logging:
  level:
    org.hibernate.SQL: debug  # logger를 통해 출력
    org.hibernate.type: trace