spring:
  datasource:
    url: jdbc:mysql://localhost:3307/trackers?serverTimezone=Asia/Seoul
    username: trackers
    password: qhddnfl
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create # 테이블을 drop하지 않음 data를 계속 쓸 수 있음
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
#        show_sql: true   # sout 으로 출력

  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            scope:
                - name
                - email
            client-name: Naver # ????? ??? ?? ????? ???? ?????.
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver # 코드를 받는 callback 주소

          google: # /oauth2/authorization/google
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response # 회원 정보를 json으로 받는데 response라는 키값으로 네이버가 리턴해줌.

  jwt:
    secret: ${JWT_SECRET}

logging:
  level:
    org.hibernate.SQL: debug  # logger를 통해 출력
    org.hibernate.type: trace