spring:
  profiles:
    group:
      blue: blue, common, secret-dev
      green: green, common, secret-dev

server:
  env: blue

---

spring:
  config:
    activate:
      on-profile: blue

server:
  port: 8080
  serverAddress: myaurora-dev.site

serverName: blue_server_dev

---

spring:
  config:
    activate:
      on-profile: green

server:
  port: 8081
  serverAddress: myaurora-dev.site

serverName: green_server_dev

---

spring:
  config:
    activate:
      on-profile: common

  security:
    oauth2:
      client:
        registration:
          naver:
            redirect-uri: https://myaurora-dev.site/login/oauth2/callback/naver
          kakao:
            redirect-uri: https://myaurora-dev.site/login/oauth2/callback/kakao
          google:
            redirect-uri: https://myaurora-dev.site/login/oauth2/callback/google
  data:
    redis:
      host: ${redis.elastiCache.host}
      port: 6379

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: false
        show_sql: false   # sout 으로 출력
        default_batch_fetch_size: 100
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0

logging:
  level:
    org.hibernate.SQL: debug  # logger를 통해 출력
    org.hibernate.type: trace

management:
  endpoints:
    web:
      exposure:
        include: '*'

  prometheus:
    metrics:
      export:
        enabled: true