spring:
  profiles:
    active: dev    # 디폴트로 로드
    include: secret-dev
    group:
      blue: blue, common, secret-dev
      green: green, common, secret-dev

server:
  env: blue

---

spring:
  config:
    activate:
      on-profile: blue
  security:
    oauth2:
      client:
        registration:
          naver:
            redirect-uri: https://myaurora-dev.site/login/oauth2/callback/naver
          kakao:
            redirect-uri: https://myaurora-dev.site/login/oauth2/callback/kakao
          google:
            redirect-uri: https://myaurora-dev.site/login/oauth2/callback/google
  data:
    redis:
      host: ${redis.elastiCache.host}
      port: 6379

server:
  port: 8080
  serverAddress: myaurora-dev.site

serverName: blue_server

---

spring:
  config:
    activate:
      on-profile: green
  security:
    oauth2:
      client:
        registration:
          naver:
            redirect-uri: https://myaurora-dev.site/login/oauth2/callback/naver
          kakao:
            redirect-uri: https://myaurora-dev.site/login/oauth2/callback/kakao
          google:
            redirect-uri: https://myaurora-dev.site/login/oauth2/callback/google
  data:
    redis:
      host: ${redis.elastiCache.host}
      port: 6379

server:
  port: 8081
  serverAddress: myaurora-dev.site

serverName: green_server

---

spring:
  config:
    activate:
      on-profile: common

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: false
        show_sql: false
        default_batch_fetch_size: 100
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

logging:
  level:
    org.hibernate.SQL: debug  # logger를 통해 출력
    org.hibernate.type: trace