spring:
  profiles:
    active: local    # 디폴트로 로드
    group:
      local: local, common, secret

server:
  env: local

---

spring:
  config:
    activate:
      on-profile: local
  security:
    oauth2:
      client:
        registration:
          naver:
            redirect-uri: http://localhost:3000/login/oauth2/callback/naver
          kakao:
            redirect-uri: http://localhost:3000/login/oauth2/callback/kakao
          google:
            redirect-uri: http://localhost:3000/login/oauth2/callback/google
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8080
  serverAddress: localhost

serverName: local_server

---

spring:
  config:
    activate:
      on-profile: common

  jpa:
    hibernate:
      ddl-auto: create # 테이블을 drop하지 않음 data를 계속 쓸 수 있음
    properties:
      hibernate:
        format_sql: false
        show_sql: false   # sout 으로 출력
        default_batch_fetch_size: 100
    defer-datasource-initialization: true
  sql:
    init:
      mode: never

logging:
  level:
    org.hibernate.SQL: debug  # logger를 통해 출력
    org.hibernate.type: trace