INSERT INTO subject (subject_id, subject_title) VALUES (1, '모두의 교육');
INSERT INTO subject (subject_id, subject_title) VALUES (2, '기본생활지원');
INSERT INTO subject (subject_id, subject_title) VALUES (3, '안정된 일자리');
INSERT INTO subject (subject_id, subject_title) VALUES (4, '건강한 삶');
INSERT INTO subject (subject_id, subject_title) VALUES (5, '인권평화와역사');
INSERT INTO subject (subject_id, subject_title) VALUES (6, '동물');
INSERT INTO subject (subject_id, subject_title) VALUES (7, '지역공동체');
INSERT INTO subject (subject_id, subject_title) VALUES (8, '더나은사회');
INSERT INTO subject (subject_id, subject_title) VALUES (9, '환경');

INSERT INTO target (target_id, target_title) VALUES (1, '아동');
INSERT INTO target (target_id, target_title) VALUES (2, '청소년');
INSERT INTO target (target_id, target_title) VALUES (3, '청년');
INSERT INTO target (target_id, target_title) VALUES (4, '여성');
INSERT INTO target (target_id, target_title) VALUES (5, '실버세대');
INSERT INTO target (target_id, target_title) VALUES (6, '장애인');
INSERT INTO target (target_id, target_title) VALUES (7, '이주민');
INSERT INTO target (target_id, target_title) VALUES (8, '다문화');
INSERT INTO target (target_id, target_title) VALUES (9, '지구촌');
INSERT INTO target (target_id, target_title) VALUES (10, '어려운이웃');
INSERT INTO target (target_id, target_title) VALUES (11, '우리사회');
INSERT INTO target (target_id, target_title) VALUES (12, '유기동물');
INSERT INTO target (target_id, target_title) VALUES (13, '야생동물');
