global:
  scrape_interval: 15s
  scrape_timeout: 15s
  evaluation_interval: 2m    # 규칙을 검증하는 간격
  external_labels:    # 수집된 모든 메트릭에 추가될 전역 레이블을 정의
    monitor: 'system-monitor'
  query_log_file: query_log_file.log    # 쿼리 로그를 저장할 파일 경로를 지정

rule_files:
  - "rule.yaml"

scrape_configs:
  - job_name: "prometheus"    # 스크랩할 작업의 이름을 지정
    static_configs:
      - targets:    # 스크랩할 정적인 타깃을 정의
          - "prometheus:9090"
  - job_name: "springboot"
    metrics_path: "/actuator/prometheus"    # 애플리케이션의 메트릭을 얻기 위한 엔드포인트 경로를 지정
    scheme: 'http'    # 스크랩할 대상의 프로토콜을 지정
    scrape_interval: 5s
    static_configs:
      - targets:
          - "app:8080"