# github repository actions 페이지에 나타날 이름
name: CI/CD using github actions & docker

# event trigger
# main이나 dev 브랜치에 pull request가 발생 되었을 때 실행
on:
  pull_request:
    branches: [ "main", "dev" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build Project with Gradle
        run: ./gradlew build -x test

      - name: Login to docker hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}

      - name: Build docker image
        run: docker build -t ${{secrets.DOCKER_USERNAME}}/trackers .

      - name: Publish image to docker hub
        run: docker push ${{secrets.DOCKER_USERNAME}}/trackers:latest

  deploy:
    needs: build
    runs-on: [ aws-ec2 ]
    steps:
      - name: Pull Image from docker hub
        run: docker pull ${{secrets.DOCKER_USERNAME}}/trackers:latest

      - name: Delete old container
        run: docker rm -f trackers-container

      - name: Run docker container
        run: docker run -d -p 8080:8080 --name trackers-container ${{secrets.DOCKER_USERNAME}}/trackers